llm_models:
  - name: "llama3-8b-8192"
    api_key: "*******GROQ_API_KEY******"
    api_base: "https://api.groq.com/openai/v1"
  - name: "gpt-3.5-turbo"
    api_key: "******OPENAI_API_KEY*****"
    api_base: "https://api.openai.com/v1"
embedding_models:
  - "all-MiniLM-L6-v2"
  - "sentence-transformers/all-mpnet-base-v2"